services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:81"
    volumes:
      - ./symfony-app:/var/www/symfony-app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: php
    ports:
      - '9000:9000'
    volumes:
      - ./symfony-app:/var/www/symfony-app
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  