app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
app_registration:
    path: /register
    controller: App\Controller\RegistrationController::register
main:
    path: /
    controller: App\Controller\MainController::index
dish.index:
    path: /dish
    controller: App\Controller\DishController::index
    methods: GET

dish.create:
    path: /dish/create
    controller: App\Controller\DishController::create
    methods: [GET, POST]

dish.show:
    path: /dish/show/{id}
    controller: App\Controller\DishController::show
    methods: GET
    requirements:
        id: \d+

dish.delete:
    path: /dish/delete/{id}
    controller: App\Controller\DishController::delete
    requirements:
        id: \d+
menu:
    path: /menu
    controller: App\Controller\MenuController::menu
order:
    path: /order
    controller: App\Controller\OrderController::index
create_order:
    path: /order/{id}
    controller: App\Controller\OrderController::order
    requirements:
        id: \d+
status:
    path: /status/{id},{status}
    controller: App\Controller\OrderController::status
    requirements:
        id: \d+
order.delete:
    path: /order/delete/{id}
    controller: App\Controller\OrderController::delete
    requirements:
        id: \d+
