main:
    path: /
    controller: App\Controller\MainController::index

article_index:
    path: /article
    controller: App\Controller\ArticleController::index
article_fetchall:
    path: /article/show
    controller: App\Controller\ArticleController::show_all

article_show:
    path: /article/{id}
    controller: App\Controller\ArticleController::show
    requirements:
        id: \d+

article_delete:
    path: /article/delete/{id}
    controller: App\Controller\ArticleController::delete
    requirements:
        id: \d+

dish:
    path: /dish
    controller: App\Controller\DishController::index
dish.create:
    path: /dish/create
    controller: App\Controller\DishController::create
dish.show:
    path: /dish/show/{id}
    controller: App\Controller\DishController::show
    requirements:
        id: \d+
dish.delete:
    path: /dish/delete/{id}
    controller: App\Controller\DishController::delete
    requirements:
        id: \d+

